# version: '3.8'
# services:
#   postgredb:
#     image: postgres:13
#     container_name: postgredb
#     # networks:
#     #   - suruse
#     # env_file:
#     #   - .env
#     # environment:
#     #   POSTGRES_PASSWORD: example
#     environment:
#       POSTGRES_USER: example
#       POSTGRES_PASSWORD: example
#       PGDATA: /data/postgres
#     ports:
#       - 7432:5432
#       # - 5438:5432
#       # - 5432:5432
#     volumes:
#       # - pgdata:/var/lib/postgresql
#       # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#       # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
#       # - ./postgres-data:/var/lib/postgresql/data
#       # host.docker.interna;l
#       # - postgres-data:/var/lib/postgresql/data
#       - ./data:/var/lib/postgresql/data
#       # - postgres:/data/postgres
#     # restart: unless-stopped
#     restart: always
#     # networks:
#     #   - postgres
#     expose:
#       - 5432
  
#   # pgadmin:
#   #   container_name: pgadmin_container
#   #   image: dpage/pgadmin4
#   #   env_file:
#   #     - .env
#   #   volumes:
#   #      - pgadmin:/var/lib/pgadmin
#   #   depends_on:
#   #     - postgres
#   #   ports:
#   #     # - "5555:80"
#   #     - 5454:5454/tcp
#   #   networks:
#   #     - suruse
#   #   restart: unless-stopped
# networks:
#   default:
#     name: postgre-service_default
#   # suruse:
#   #   driver: bridge
# # volumes:

#   # pgdata:
#   # pgadmin:
#   # postgres-data:
# # volumes:
# #   pgdata:

version: '3.8'
services:
 db:
   container_name: postgres_container
   image: postgres
   restart: always
   environment:
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     PGDATA: ${PGDATA}
    #  POSTGRES_DB: postgres_db
    #  POSTGRES_USER: admin
    #  POSTGRES_PASSWORD: secret
    #  PGDATA: /var/lib/postgresql/data
   ports:
    #  - 5432:5432
     - 7432:5432
   volumes:
     - db-data:/var/lib/postgresql/data
    #  expose:
    #     - 5432
  #  env_file:
  #     - ./.env.prod
  #     - ./.env

 pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
     PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    #  PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #  PGADMIN_DEFAULT_PASSWORD: secret
    #  PGADMIN_LISTEN_PORT: 80
   ports:
     - 8080:80
   volumes:
     - pgadmin-data:/var/lib/pgadmin
  #  env_file:
  #     - ./.env.prod
  #     - ./.env

networks:
  postgres:
    driver: bridge
volumes:
  db-data:
  pgadmin-data: